ALTER TABLE chatadvices
    ADD COLUMN id BIGSERIAL PRIMARY KEY;
ALTER TABLE chatjokes
    ADD COLUMN id BIGSERIAL PRIMARY KEY;
ALTER TABLE chatmemes
    ADD COLUMN id BIGSERIAL PRIMARY KEY;
ALTER TABLE chatfeatures
    DROP CONSTRAINT pk_chatfeatures;
ALTER TABLE chatfeatures
    ADD COLUMN id BIGSERIAL PRIMARY KEY;
COMMIT;